"""
Main orchestration flow for handling a natural-language database question.

This module coordinates the full pipeline:
1. Prompt injection screening.
2. SQL generation from the user question.
3. SQL validation and safety hardening.
4. SQL execution against the database.
5. Natural-language answer generation from query results.
"""

from app.security.injection_checks import (
    check_prompt_injection,
    PromptInjectionError,
)
from app.services.sql_generation_service import generate_sql
from app.security.sql_validator import validate_sql, SQLValidationError
from app.security.guardrails import ensure_limit
from app.db.executor import execute_query
from app.services.answer_service import generate_natural_answer


def handle_question(question: str) -> dict:
    """
    Process a user question end-to-end and return structured outputs.

    Returns a dictionary containing:
    - question: the original user input
    - sql: the validated and limit-safe SQL query
    - result: tabular result payload from the database executor
    - answer: final human-readable answer generated by the LLM
    """
    # Block obvious prompt-injection attempts before any LLM or SQL work.
    check_prompt_injection(question)

    # Generate SQL from natural language, then validate and harden it.
    raw_sql = generate_sql(question)
    validated_sql = validate_sql(raw_sql)
    safe_sql = ensure_limit(validated_sql)

    # Execute the SQL and synthesize a final natural-language response.
    result = execute_query(safe_sql)
    answer = generate_natural_answer(question, safe_sql, result)

    return {
        "question": question,
        "sql": safe_sql,
        "result": result,
        "answer": answer,
    }
